# Namespace for all resources
namespace: "default"

# Database configuration
# Supported types: psql, mysql, mongo
# Place all DB credentials and config here

# Example:
# db:
#   type: psql
#   host: mydb.example.com
#   name: mydatabase
#   username: myuser
#   password: mypass

db:
  type: "psql"           # psql, mysql, mongo
  host: "<DB_HOST>"
  name: "<DB_NAME>"
  username: "<DB_USERNAME>"
  password: "<DB_PASSWORD>"

# Backup configuration
backup:
  retentionDays: 7
  schedule: "0 2 * * *"   # Cron schedule for backup job

# AWS S3 configuration
aws:
  accessKeyId: "<AWS_ACCESS_KEY_ID>"
  secretAccessKey: "<AWS_SECRET_ACCESS_KEY>"
  region: "<AWS_REGION>"
  bucket: "<S3_BUCKET>"
  path: ""

# MinIO configuration
minio:
  endpoint: "<MINIO_ENDPOINT>"
  bucket: "<MINIO_BUCKET>"
  accessKey: "<MINIO_ACCESS_KEY>"
  secretKey: "<MINIO_SECRET_KEY>"

# Azure Blob Storage configuration
azure:
  storageAccount: "<AZURE_STORAGE_ACCOUNT>"
  storageKey: "<AZURE_STORAGE_KEY>"
  container: "<AZURE_CONTAINER>"
  path: "<AZURE_PATH>"

# Notification configuration
notification:
  teamsWebhookName: "<TEAMS_WEBHOOK_NAME>"
  teamsWebhookUrl: "<TEAMS_WEBHOOK_URL>"

# Output provider: aws, azure, minio
outputProvider: "minio"

# Resources for the backup job
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "1000m"
